---
title: "2025 Changes to U.S. Climate-Relevant Policy"
subtitle: ""
format:
 revealjs:
#   footer: "(more at [judgelord.github.io/PP495/policy](https://judgelord.github.io/PP495/policy#/title-slide) )"
   incremental: false   
   smaller: false
   scrollable: true
   theme: [michigan.scss, oil.scss]
css: styles.css
execute:
  echo: false
  engine: knitr
---

## TL;DR 

- Big governmental support for oil, gas, and mining, including:
    - using the military to aid transport and refining
    - price supports and subsidies, including for private pipelines
    - taking private property (e.g., for pipelines)
- Ban offshore wind and redefine wind & solar as not "energy"
- End support for water, fuel, or energy efficiency
- Expedite pollution permits and health/safety/cost review^[Directing legal compliance questions to courts (but also reducing judicial oversight?)]
- Expand oil, gas, and mining on public lands
- Rescind requirements to disclose climate risks
- End international cooperation on climate change

# Jan. 20, 2025 E.O.s^[Note: Executive Orders are generally not legally-binding policy, but rather orders to Executive Branch officials with policymaking authority spelled out in laws passed by Congress. Federal courts may or may not agree that these officials have the statutory or constitutional authority to do some of these things. E.O.s tend to be broad statements of policy wrapped in rhetorical flourish. Courts don't generally intervene until the details are worked out and specific effects are clear. These slides aim to summarize their intended effects in plain language.] {background-opacity="0.15" background-image="https://cdnph.upi.com/svc/sv/upi/5181737412928/2025/1/ba7cfd24d739668d1a4ab54268a90a04/President-Trump-signs-executive-orders-before-inaugural-crowd-at-Capital-One-Arena.jpg"}



## ["Energy Emergency" E.O.](https://www.whitehouse.gov/presidential-actions/2025/01/declaring-a-national-energy-emergency/) {background-opacity="0.3" background-image="https://www.gannett-cdn.com/-mm-/7943967a784f994f95931170ff2923f74c7e0899/c=0-139-2000-1269&r=x1683&c=3200x1680/local/-/media/2016/08/01/USATODAY/USATODAY/636056598017637651-AP-California-Wildfires.14.jpg"}

To promote oil, gas, biofuels, nuclear, and mining,^[More specifically, “energy” is defined as "crude oil, natural gas, lease condensates, natural gas liquids, refined petroleum products, uranium, coal, biofuels, geothermal heat, the kinetic movement of flowing water, and critical minerals"] government agencies should:

Sec. 2. Consider using eminent domain & the Defense Production Act to commandeer private lands and companies^[The Brennan Center has a great summary of [Emergency Powers](https://www.brennancenter.org/our-work/research-reports/guide-emergency-powers-and-their-use). Interestingly, this Energy Emergency E.O. does not mention that a Governor of a State may petition the President to suspend any part of a Clean Air Act implementation plan or any requirement under Section 110(f) (42 U.S.C. § 7651j), which Carter granted to fossil fuel power plants during [regional energy emergencies in the 1970s](https://www.npr.org/2025/01/20/nx-s1-5268653/energy-emergency-trump-oil-evs).]

Sec. 3-6. Exempt projects from normal health/safety/cost review

- Emergency approvals of public lands leases, pollution permits <!--, production, transportation, refining--> 
- Waive Clean Water Act protections for water quality, wetlands, & coastlines^[As I read it, the emergency powers of the CWA focus emergency *restrictions* to prevent contamination/poisoning, not to permit it.]
- Emergency exemptions from Endangered Species Act restrictions on impacts that cause extinctions
  
Sec. 7. Mobilize the military to build oil and gas infrastructure and aid oil and gas transport and refining 


**Is it following the Project 2025 playbook?** 

> ✘ "**Stopping executive overreach.** Congress should set policy---not Presidents through pen-and-phone executive orders, and not agencies through regulations and guidance. National emergency declarations should expire absent express congressional authorization within 60 days after the date of the declaration." - Project 2025

## Further Energy Emergency Policy {background-opacity="0.3" background-image="https://bloximages.chicago2.vip.townnews.com/wyomingnews.com/content/tncms/assets/v3/editorial/c/69/c69d4e56-33ee-470f-bde6-c235daa20b1e/68acbec11dfd0.image.jpg?resize=990%2C743"}



- Army Corps fast-tracks CWA permits for Line 5 and  Blue Marlin pipelines, [legal argument unclear](https://www.nytimes.com/2025/02/19/climate/army-corps-engineers-fossil-fuel-permits.html)
- [DOI approves uranium mine](https://perkinscoie.com/insights/update/doi-exercises-authority-under-novel-emergency-authorities-approve-uranium-mine) in [11 days](https://www.blm.gov/press-release/interior-expedites-permitting-critical-energy-project-address-national-energy)
- [Black Butte Coal Mine Expansion](https://www.doi.gov/pressreleases/trump-administration-accelerates-review-black-butte-mine-expansion-bold-step-energy) approved in [28 days](https://www.wyomingnews.com/laramieboomerang/news/feds-reactivate-440-million-ton-coal-lease-application-in-powder-river-basin/article_224ab7ae-8f02-4bbb-85d4-513893d15c94.html)
- West Antelope II & III coal emergency leases
- DOE emergency orders [keep the J.H. Campbell coal power plant open in Michigan](https://www.detroitnews.com/story/news/local/michigan/2025/08/21/trump-administration-extends-order-keeping-michigan-coal-plant-open/85748180007/). FERC approves Consumers Energy's request to allocate costs to electricity bills across the Midwest.

> DOE Press Secretary: President Donald Trump and Secretary Wright "are ensuring Americans have access to all forms of reliable energy, including coal"


## [American Energy E.O.](https://www.whitehouse.gov/presidential-actions/2025/01/unleashing-american-energy/)  {background-opacity="0.3" background-image="https://heartlanddailynews.com/wp-content/uploads/2021/03/LNG-export-terminal.jpg"}

To promote oil, gas, coal, hydro, biofuels, mining, and nuclear industries, government agencies should:

Sec. 2. 

- Direct more federal funds to 
  - offshore oil and gas
  - mining 
- Use no federal funds for 
  - energy efficiency 
  - water efficiency
  - fuel efficiency 
  - electrification, especially not anything related to EVs^[By “electric vehicle (EV) mandate,” this E.O. means (1) the part of the Clean Air Act that [allows](https://www.law.cornell.edu/uscode/text/42/7543) California to set its own fuel economy standards for cars and trucks (also being attacked in the [courts](https://www.cbsnews.com/news/supreme-court-california-epa-waiver-vehicle-emissions-standards/) ), and (2) IRA subsidies for EVs and other technologies that effectively make EVs cheaper and thus "other types of vehicles affordable." More from NPR [here](https://www.npr.org/2025/01/30/nx-s1-5272749/donald-trump-ev-electric-vehicles-subsidies-auto-industry)]
- Not consider international effects in policymaking

Sec. 3-4. Deregulate oil, gas, coal, hydro, biofuels, mining, and nuclear industries

Sec. 5. Eliminate or expedite environmental review and permitting

- Replace all binding rules implementing the National Environmental Policy Act with nonbinding guidance.^[Environmental Impact Statements will still be required by NEPA (a statute), but I don't see anything in the [NEPA text](https://www.energy.gov/sites/default/files/2023-08/NEPA%20reg%20amend%2006-2023.pdf) requiring any agency to write binding rules governing EIS.] (NEPA compliance will thus be more often decided by courts.) 
- Reduce judicial review of legal compliance (e.g., NEPA)^[What courts can review is generally up to Congress and the courts (or so say the courts at least). I'm curious if there is a policy or legal argument here.]
- Draft recommendations to Congress on pipeline permitting and construction


Sec. 6. Change cost-benefit analysis 

  - Exclude the [social costs of pollution](https://news.bloomberglaw.com/environment-and-energy/trump-aims-to-end-carbon-metric-that-puts-price-on-climate-harms)
  - Exclude [co-benefits](https://www.sciencedirect.com/science/article/pii/S1462901115301064) of reducing pollution 
  - Exclude [international effects](https://www.yalejreg.com/nc/internationalizing-regulatory-review-by-elena-chachko/)
  - Use higher discount rates (further down-weighting costs and benefits for future generations)
  
Sec. 7. Pause the disbursement of funds appropriated through the Bipartisan Infrastructure Law and Inflation Reduction Act.^[On Jan 21, OMB [clarified](https://www.whitehouse.gov/briefings-statements/2025/01/omb-memo-m-25-11/) that this only applies to funds supporting programs, projects, or activities that may be implicated by the policy established in Section 2"]

- Especially no money for electric vehicle charging stations

Sec. 8. Approve gas export projects

- Skip NEPA review if possible

Sec. 9. Help companies do more mining on public lands.

- More government funds to locate minerals for companies to mine
- More government funds for mining projects
- Increase National Defense Stockpile of minerals to increase demand and provide supply when there is scarcity in the market

> "**Strategic National Stockpile.** The President should invoke the Defense Production Act, which is a form of temporary takeover of private enterprises, only in the gravest circumstances...The SNS should clarify its mission as supplier of last resort to the federal government, state governments, or first responders."  - Project 2025" 


## Big Beautiful Bill repeals much of IRA 

- [Rescinds $60 million in unspent funds at NOAA for atmospheric, climate, and weather research](https://www.nytimes.com/2025/07/13/climate/floods-trump-cuts-disaster-preparedness-fema.html)
- Republican Senators successfully pushed for slightly slower tax credit phase-outs to limit the disruption to industry
    -  But an [E.O.](https://www.nytimes.com/2025/07/10/climate/trump-renewable-energy-solar.html) instructed the Treasury Department to limit the ability of wind and solar projects to qualify for the fast-disappearing tax credits (legality debated)
- Limits tax credits for projects that source materials or rely on investments from certain countries
-  repeals the Greenhouse Gas Reduction Fund and rescinds all "unobligated" funds.
   - EPA claimed new authority to claw back billions of dollars in funding contracted for renewable energy and efficiency projects, arguing it de-obligated $17 billion in grant funds when it issued termination letters canceling the contracts.
- Pay to play - NEPA review in 180 days


## Big Beautiful Bill upends Farm Bill

Historically, 5-year farm bills are bipartisan legislation with subsidies for farmers (rural) + food assistance programs that boost demand and reduce malnutrition (rural + urban) 

- Cuts $186 billion in food assistance (SNAP) from 22.3 million families - [2.4 million families projected to lose food assistance entirely](https://www.cnbc.com/2025/09/01/snap-benefit-cuts-americans-food-grocery-shopping.html)
   - added work requirements for individuals ages 55 through 64, parents of children ages 14 and up, and veterans.
- +$65 billion in subsidies (mostly crop insurance)
- expanded eligibility to include larger non-farm corporations, likely accelerating farmland consolidation (fewer family farms)
- did not cut most conservation programs, rescinds unobligated forestry and conservation funds from the IRA for grants to non-federal forest landowners and $101 million from Urban and Community Forestry Assistance grants. 

Other traditional parts of the Farm Bills were left out. Without further legislation, there will be large cuts to

- National Institute of Food and Agriculture
- Agricultural Research Service
- Animal and Plant Health Inspection Service
- Agricultural Marketing Service
- Risk Management Agency
- Farm Service Agency
- Natural Resources Conservation Service
- Food and Nutrition Service


## Rules implementing Energy E.O.

- "Removal of National Environmental Policy Act Implementing Regulations" removes  Trump 1.0-era CEQ rules. 
- Some agencies made new rules (including DOI, DOT, DOE, USDA, FERC). Others switched to "operating procedures" (guidance). 
- All cut public participation and consideration of climate, equity, and cumulative impacts. 
- New categorical exclusions (e.g., based on project cost).

## Further Energy Policy 

- [Despite court orders](https://www.nytimes.com/2025/02/10/us/trump-unfreezing-federal-grants-judge-ruling.html) and [more court orders](https://thehill.com/homenews/administration/5216594-appeals-court-keeps-block-on-trumps-sweeping-funding-freeze/), disbursement of funds appropriated through the Bipartisan Infrastructure Law and Inflation Reduction Act has been frozen since Feb. 2025. <!--For example, the Office of Energy Efficiency and Renewable Energy has posted almost [no new ]( https://www.energy.gov/eere/funding/eere-funding-opportunities)--> 
- [Approval of CA vehicle emissions rules "recended" with no plan to follow the CA exemption portion of the Clean Air Act](https://www.kqed.org/science/1997300/trump-blocks-californias-ev-rules-state-sues-in-response). The Senate Parliamentarian and the Government Accountability Office say this is not legal.

## [Alaska's Resouces E.O.](https://www.whitehouse.gov/presidential-actions/2025/01/unleashing-alaskas-extraordinary-resource-potential/) {background-opacity="0.15" background-image="https://1.bp.blogspot.com/-77DHTEAHfdE/TkXAzD8UDoI/AAAAAAAAASU/f3klXPyJjoo/s1600/alaska.jpg"}

Government agencies should: 

- Expedite permitting and leasing, especially for gas export and pipelines
- Exempt gas export from regulations 
- Open the Arctic National Wildlife Refuge to oil and gas extraction
- Replace many 2024 Environmental Impact Statements with 2020 versions
- Remove protections for subsistence resources
- Deny the request for an Indigenous sacred site in the Coastal Plain of the Arctic National Wildlife Refuge
- Permit more hunting and fishing on federal lands
- Support companies operating the failing Trans-Alaska Pipeline
- Build more roads in National Forests 

## [Wind Projects E.0.](https://www.whitehouse.gov/presidential-actions/2025/01/temporary-withdrawal-of-all-areas-on-the-outer-continental-shelf-from-offshore-wind-leasing-and-review-of-the-federal-governments-leasing-and-permitting-practices-for-wind-projects/) {background-opacity="0.15" background-image="https://forefrontaalborg.com/wp-content/uploads/2022/05/AdobeStock_366215509-2048x1069.jpg"}

Government agencies should: 

- Temporarily (?) ban new offshore wind ("until this Presidential Memorandum is revoked.")^[Biden similarly [succeeded](https://apnews.com/article/biden-louisiana-new-orleans-gulf-of-mexico-b209a922546aefb35595dfe920b63b60) in banning *new* offshore oil and gas] 
  - prevents consideration of any wind energy lease renewal
  - does not apply to oil, gas, minerals
- Review existing permits/leases to identify legal bases for terminating existing wind energy leases
- Impose a moratorium on all activities and rights of Magic Valley Energy granted by the Bureau of Land Management's 2024 approval of the Lava Ridge Wind Project
- Require developers to pay for the removal of old windmills

## {background-opacity="0.15" background-image="https://forefrontaalborg.com/wp-content/uploads/2022/05/AdobeStock_366215509-2048x1069.jpg"}

> "We're not allowing any windmills to go up. We don't allow windmills, and we don't want the solar panels...we are just not going to allow them...I hope they get back to fossil fuels" - President Trump, [Aug. 25 2025](https://www.youtube.com/watch?v=sp97kSwaBfQ) 


## Further Wind Policy Developments {background-opacity="0.15" background-image="https://forefrontaalborg.com/wp-content/uploads/2022/05/AdobeStock_366215509-2048x1069.jpg"}


- Department of the Interior to put [all wind and solar projects through “elevated review”](https://grist.org/energy/trumps-interior-department-is-turning-environmentalists-legal-playbook-against-them/) from the Secretary's office, and may assert that the purpose of windmills is to [kill protected birds](https://heatmap.news/plus/the-fight/spotlight/migratory-bird-act-trump?utm_source=substack&utm_medium=email#), making them illegal
- DOI [cancels the lease for Lava Ridge Wind Project signed with BLM in 2024](https://www.doi.gov/pressreleases/interior-department-moves-cancel-reckless-biden-era-approval-lava-ridge-wind-project)
- Bureau of Ocean Energy Management [orders developers to halt work on an 80%-finished wind farm](https://www.npr.org/2025/08/23/nx-s1-5513919/trump-stops-offshore-wind-renewable-energy), costing shareholders $2.4 billion
- Another company ordered to halt construction estimated regulatory delays cost $1 billion (its lease was signed in 2017, with the first Trump administration). [1,500 jobs were threatened.](https://www.equinor.com/news/20250417-suspends-offshore-construction-activities-empire-wind)
-  Internal Revenue Service guidance [bars companies building wind and solar projects from federal tax incentives](https://www.nytimes.com/2025/08/15/climate/irs-wind-solar-tax-credits.html)
-  Commerce Department considering [banning imports of wind turbines](https://public-inspection.federalregister.gov/2025-16191.pdf?utm_campaign=pi+subscription+mailing+list&utm_medium=email&utm_source=federalregister.gov)
- Bureau of Ocean Energy Management [rescinded all designated Wind Energy Areas along the continental shelf](https://www.boem.gov/newsroom/notes-stakeholders/boem-rescinds-designated-wind-energy-areas-outer-continental-shelf)
- The Department of Transportation Department [terminated upgrades to ports required for offshore wind development](https://www.npr.org/2025/08/31/nx-s1-5522943/trump-offshore-wind-energy-ports) funded by the Bipartisan Infrastructure Law's Nationally Significant Freight and Highway Projects (INFRA) and Port Infrastructure Development Program (PIDP) grant programs 
- DOT is also recommending [1.2-mile minimum setback requirements for wind farms near federal highways and railroads](https://www.nytimes.com/2025/08/07/climate/trump-wind-solar-power-projects.html?smid=nytcore-ios-share&referringSource=articleShare) 
- The Federal Aviation Administration is re-evaluating whether wind farms pose a danger to aviation. Such a declaration would allow a full-scale ban of modern windmills (95% on private land)

## Similar policies targeting solar {background-opacity="0.15" background-image="https://i2-prod.liverpoolecho.co.uk/incoming/article31278176.ece/ALTERNATES/s615/0_Solarpanels.jpg"}


- Solar facilities on private land are being delayed because federal agencies have halted water permits
- Where Interior permits are required, solar projects on private land go through political review by the Secretary, [costing companies tens of millions of dollars](https://www.nytimes.com/2025/08/07/climate/trump-wind-solar-power-projects.html?smid=nytcore-ios-share&referringSource=articleShare)

> “not only stopped solar development on federal lands in Nevada, but also on private land where federal approvals such as transmission line rights of way are required.” - Joe Lombardo, Governor of Nevada


## [International Environmental Agreements E.O.](https://www.whitehouse.gov/presidential-actions/2025/01/putting-america-first-in-international-environmental-agreements/) {background-opacity="0.15" background-image="https://www.connect4climate.org/sites/default/files/images/event/unfccc-bonn_0.jpg"}

Instructs agency officials to: 

- Withdraw the U.S. from the Paris Agreement 
- End all funds and commitments to the United Nations Framework Convention on Climate Change
- Freeze and end funds for U.S. International Climate Finance (i.e., loans)

<!--
## [People over Fish E.O.](https://www.whitehouse.gov/presidential-actions/2025/01/putting-people-over-fish-stopping-radical-environmentalism-to-provide-water-to-southern-california/)

More completely stop water from the  Sacramento and San Joaquin rivers from flowing into the Ocean, directing more water to lawns and crop irrigation.

--> 


## [Rescissions of "Harmful E.O.s" E.O.](https://www.whitehouse.gov/presidential-actions/2025/01/initial-rescissions-of-harmful-executive-orders-and-actions/)  {background-opacity="0.15" background-image="https://images.inc.com/uploaded_files/image/1920x1080/getty_635923424_360310.jpg"}

Rescinds nearly all Biden E.O.s^[including mundane things like the order of succession at the Department of Agriculture and outdated things like reopening schools and offices after the pandemic] 

**Highlights:** Federal agencies should: 
 
- Rescind restrictions on leasing for oil and gas offshore and on public land
- Rescind requirements to disclose climate risks

Climate-Related E.O.s rescinded: 

- Executive Order 13990 of January 20, 2021 (Protecting Public Health and the Environment and Restoring Science To Tackle the Climate Crisis).
- Executive Order 14007 of January 27, 2021 (President’s Council of Advisors on Science and Technology).
- Executive Order 14008 of January 27, 2021 (Tackling the Climate Crisis at Home and Abroad).
- Executive Order 14027 of May 7, 2021 (Establishment of the Climate Change Support Office).
- Executive Order 14030 of May 20, 2021 (Climate-Related Financial Risk).
- Executive Order 14057 of December 8, 2021 (Catalyzing Clean Energy Industries and Jobs Through Federal Sustainability).
- Executive Order 14082 of September 12, 2022 (Implementation of the Energy and Infrastructure Provisions of the Inflation Reduction Act of 2022).
- The Presidential Memorandum of March 13, 2023 (Withdrawal of Certain Areas off the United States Arctic Coast of the Outer Continental Shelf from Oil or Gas Leasing).
- Executive Order 14094 of April 6, 2023 (Modernizing Regulatory Review).
- Executive Order 14096 of April 21, 2023 (Revitalizing Our Nation’s Commitment to Environmental Justice for All).

## [E.0. 13957 "Schedule F"](https://www.whitehouse.gov/presidential-actions/2025/01/restoring-accountability-to-policy-influencing-positions-within-the-federal-workforce/) {background-opacity="0.15" background-image="https://www.shatteringtheceiling.com/wp-content/uploads/2016/10/federal_employees.jpg"} 
<!--https://www.shatteringtheceiling.com/wp-content/uploads/2016/10/federal_employees.jpg--> 

Reclassifies thousands (~50,000? 100,000?) competitive civil servants (merit-based) positions as "Exempt" --- more like political appointees who serve at the pleasure of the president and can be fired and replaced at any time.

- federal employees involved in "policy-determining, policymaking, or policy-advocating"
- anyone supervising such employees
- any other employees an agency director wants included

Directs the Office of Personnel Management to rescind its 2024 rule “Upholding Civil Service Protections and Merit System Principles” and (in clear contradiction of the Administrative Procedure Act) declares that rule "inoperative and without effect."

## Further developments 

- [In April, the Trump administration dismissed hundreds of scientists and experts](https://www.nytimes.com/2025/04/28/climate/national-climate-assessment-authors-dismissed.html)

# Other E.O.s


## [Council to Assess the Federal Emergency Management Agency](https://www.whitehouse.gov/presidential-actions/2025/01/council-to-assess-the-federal-emergency-management-agency/)	{background-opacity="0.15" background-image="https://upload.wikimedia.org/wikipedia/commons/f/ff/FEMA_-_34427_-_FEMA_community_relations_worker_helping_a_young_resident_in_New_Jersey.jpg"}

Establishes a council to look for political bias in disaster responses, chaired by [Pete Hegseth](https://en.wikipedia.org/wiki/Pete_Hegseth) and [Kristi Noem](https://en.wikipedia.org/wiki/Kristi_Noem)


- On Jan. 24, Trump suggested [eliminating FEMA](https://www.nytimes.com/2025/01/24/briefing/trump-visits-disaster-areas-high-egg-prices.html)
- Kristi Noem in March: “We are going to eliminate FEMA.”
- After flooding in Texas and [FEMA also failed to answer nearly two-thirds of calls to its disaster assistance line](https://www.nytimes.com/2025/07/11/climate/fema-missed-calls-texas-floods.html) in July, officials began talking about [fixing FEMA](https://www.nytimes.com/2025/07/11/us/politics/trump-fema-texas-flood.html).
- 20 percent of the coordinating officers who manage responses to major disasters have been terminated
- In violation of post-Katrina laws, [key positions at FEMA are staffed with people with no disaster response experience](https://www.nytimes.com/2025/08/25/climate/fema-employees-letter-trump-katrina.html?smid=nytcore-ios-share&referringSource=articleShare)
- [Revoked $3.6 billion in grants from FEMA to hundreds of communities around the country, which were to be used to help these areas protect against hurricanes, wildfires, and other catastrophes](https://www.nytimes.com/2025/07/13/climate/floods-trump-cuts-disaster-preparedness-fema.html)
- Employees say FEMA has [eliminated all gains in Hurricane response since Katrina](https://www.nytimes.com/2025/08/25/climate/fema-employees-letter-trump-katrina.html?smid=nytcore-ios-share&referringSource=articleShare)


**Following the Project 2025 playbook?** 

> ✔️ "[O]pportunities include privatizing TSA screening and the Federal Emergency Management Agency (FEMA) National Flood Insurance Program, reforming FEMA emergency spending to shift the majority of preparedness and response costs to states and localities instead of the federal government, eliminating most of DHS’s grant programs, and removing all unions in the department for national security purposes."  - Project 2025

# Further Developments 


## [Endangerment finding](https://www.epa.gov/sites/default/files/2016-08/documents/endangerment_tsd.pdf) {background-opacity="0.15" background-image="https://ichef.bbci.co.uk/news/1536/cpsprodpb/EE21/production/_116516906_temp_rises_since_1850_gra640-nc.png"}


- By declaring that [greenhouse gases pose no threat to public health](https://www.nytimes.com/2025/07/29/climate/epa-endangerment-finding-repeal-proposal.html), the EPA asserts there is [no scientific (and thus, legal) basis for all existing policies regulating greenhouse gases](https://www.nytimes.com/2025/08/03/climate/trump-epa-endangerment-finding-climate-change.html)

> "the largest deregulatory action in the history of the United States,” - Lee Zeldin


## Deleting Climate and Weather Data  {background-opacity="0.3" background-image="https://www.usatoday.com/gcdn/authoring/authoring-images/2025/04/02/USAT/82779913007-ernesto.jpg"}


- Some National Weather Service forecast offices are no longer staffed overnight, and others have been launching fewer weather balloons, which send data to feed forecasts. It is preparing for [“degraded operations.”](https://www.nytimes.com/2025/04/16/climate/national-weather-service-forecast-doge-trump.html)
- National Weather Service issued warnings for flooding in Texas on July 4 [the person in charge of communicating with local emergency managers was let go and not replaced](https://www.nytimes.com/2025/07/13/climate/floods-trump-cuts-disaster-preparedness-fema.html)
- [Farmers Sue Over Deletion of Climate Data From Government Websites](https://www.nytimes.com/2025/02/24/climate/agriculture-farmer-website-data-lawsuit.html)


## Spending freezes and clawbacks {background-opacity="0.2" background-image="https://static.vecteezy.com/system/resources/thumbnails/040/707/108/small_2x/ai-generated-abstract-ice-background-blue-background-with-cracks-on-the-ice-surface-idea-generative-ai-photo.jpg"}

- [continuing despite court orders ](https://www.nytimes.com/2025/02/19/us/politics/trump-foreign-aid-freeze.html)
-  Next Generation Warning System grantees receive stop-work order on emergency alert systems. The money was then clawed back by Congress in July, leaving [stations that serve rural areas with bills for backup generators and transmitters purchased for incomplete emergency alert systems.](https://www.npr.org/2025/08/28/nx-s1-5519337/public-media-emergency-alert-funding)
-  Oct 2025, President said if Democrats did not vote for his funding bill, he would “do things that are irreversible, that are bad for them.” The DOE then claimed to [cancel contracts for Hydrogen hubs, grid upgrades, and research in Democrat-led states](https://www.nytimes.com/2025/10/02/climate/doe-clean-energy-programs-shutdown.html) (legal argument unclear)


## New Policy from the Supreme Court  {background-opacity="0.1" background-image="https://www.motherjones.com/wp-content/uploads/2025/10/20251003_scotus-dual-state_2000b.jpg"}

- *Seven County Infrastructure Coalition v. Eagle County* - (1) more deference in NEPA + (2) NEPA review need not (can't?) consider upstream or downstream effects (e.g., climate change and environmental justice)

> "An EIS is relevant only to the question of
whether an agency’s final decision (here, to approve the
railroad) was reasonably explained." 

> "[Indirect effects] may be factually
foreseeable, but that does not mean that those effects are
relevant to the agency’s decisionmaking process"




# Policies Under Consideration 


## The 2026 Proposed Budget 

- eliminates about $882 million in the Building Resilient Infrastructure and Communities grant program, which helped support resources like flood control systems, wildfire prevention, and storm water management upgrades
- [ends collection of greenhouse gas data after 70 years](https://www.nytimes.com/2025/07/17/climate/budget-cuts-climate-observatories.html)
- Proposed budget to close 10 laboratories run by the National Oceanic and Atmospheric Administration that research the ways a warming planet is changing weather, including [firing Miami teams of “hurricane hunters”](https://www.nytimes.com/2025/07/13/climate/floods-trump-cuts-disaster-preparedness-fema.html)
- The proposed budget would also [end funding for river gauges and cancel the leases for 25 of the roughly 100 water science research facilities that predict floods.](https://www.nytimes.com/2025/07/13/climate/floods-trump-cuts-disaster-preparedness-fema.html)



## [H.R. 3898 - the PERMIT act](https://www.congress.gov/bill/119th-congress/house-bill/3898) {background-opacity="0.15" background-image="https://fox11online.com/resources/media2/16x9/1920/986/center/90/d95c56b1-d7fa-4a0d-b191-f404ab72736a-MILWAUKEEFLOODINGVO.transfer_frame_533.jpeg"}

Allows building on most wetlands without a permit by limiting Clean Water Act protections, judicial review of permits, and state and local governments' ability to protect wetlands. <!--by redefining navigable waters to exclude (1) waste treatment systems, (2) ephemeral features that flow only in direct response to precipitation, (3) prior converted cropland, (4) groundwater, or (5) any other features determined to be excluded by the U.S. Army Corps of Engineers.--> 

- **removes all protections** for groundwater, streams, and wetlands that dry out between rain events, streams and wetlands near farmland, and **any other waters or wetlands determined to be excluded** by the Army Corps
- prohibits states from considering factors other than local water quality (e.g., climate change) in 401 permitting
- shifts EPA's role from public health to minimizing costs to industry 
- limits public comment on and challenges to permits 
- shield polluters from liability 
- removes restrictions on pesticides
- reduces judicial review of permitting by vastly shortening the statute of limitations, limiting standing to file suit, and limiting the 
Court's options for recourse.
Increases procedural barriers to establishing water quality criteria and increases opportunities for litigation.

## 2026 National Defense Authorization

- "Climate resilient" changed to "resilient"
- Little indication that DOD is backing away from transition to electric vehicles and climate adaptation plans
- 2025 Authorization Bill bans DOD from requiring contractors to disclose GHG emissions


## Links for more context 

<!--https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fm.media-amazon.com%2Fimages%2FI%2F61X4RoMGBtL._SY522_.jpg&f=1&nofb=1&ipt=5bed1e068b0dd6e9098f84809cebeb5168d73c1016ecc1effe0130b9059871c4&ipo=images--> 

- "2024 Brought the World to a Dangerous Warming Threshold. Now What? Global temperatures last year crept past a key goal, raising questions about how much nations can stop the planet from heating up further." - [NYT](https://www.nytimes.com/interactive/2025/01/09/climate/2024-heat-record-climate-goal.html)
- <https://eelp.law.harvard.edu/tracker-type/regulatory-tracker/>


<!--


# Outstanding questions 


## Attempt to end [congestion pricing in NYC](https://www.nytimes.com/2025/01/30/nyregion/nyc-trump-congestion-pricing.html)

- [Update](https://www.nytimes.com/2025/02/19/us/politics/trump-king-image.html)
--> 


